db.merchant.executor.queue-capacity: 1000
spring:
  application:
    name: db-merchant
  datasource:
    name: merchant
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${MERCHANT_POSTGRES_DBNAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1 # now only one active session
      connection-timeout: 10000 # 10 sec

server:
  tomcat:
    threads.max: 50
    connection-timeout: 1s
    keep-alive-timeout: 1s
  port: ${MERCHANT_PORT}